# Generated by Django 5.0.1 on 2024-01-22 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userpost_post_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
