# Generated by Django 5.0.1 on 2024-01-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, upload_to='uploads/mediapost'),
        ),
    ]
