# Generated by Django 5.0.1 on 2024-01-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0002_alter_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreaction',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
