# Generated by Django 5.0.1 on 2024-01-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0006_usermessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
