# Generated by Django 5.0.1 on 2024-01-31 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0008_remove_post_title_userconversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserConversation',
        ),
    ]
