# Generated by Django 5.0.1 on 2024-01-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraction', '0011_rename_message_userconversation_applicant_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconversation',
            old_name='applicant_message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='userconversation',
            name='user_message',
        ),
    ]
